package com.stock.capital.enterprise;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.system.ApplicationPidFileWriter;
import org.springframework.cloud.client.discovery.EnableDiscoveryClient;

@SpringBootApplication(scanBasePackages = "com.stock")
@EnableDiscoveryClient
public class Application {

    public static void main(String[] args) {
        SpringApplication springApplication = new SpringApplication(Application.class);
        springApplication.addListeners(new ApplicationPidFileWriter());
        springApplication.run(args);
        com.spire.license.LicenseProvider.setLicenseKey("xi+hYQEAx1IrzncnAP21WMoeLVe7SH2XXP0GJYnbZKrC4SMSo/ThpDRsJAMXpR15EjQ5KaLzcPRK919KbMo37n0bV8fDWW6BU/fceLRiT0rdKmQDz/sn+f1KzyJTT8WpcLRDQLUI4PAepbXn8SrvnXTHLkNA22HSqYIIsTDxrdKlaDp6sfYakRzo1nI30LyE5gCuwy6AGw9wshSYA+wWqri7nRn7iHBR/vRE9Ew6oLMYYFxMfzJbbTHyyqgWaOBjSHsKKphC8ZMZXtQb+dMedqmTdsguUfMkQBEPebLWuV0XgH/FkzpM7KduEyniHRoplrkFr6VcAM3ZwdREM+YjdRf3BNzZyKWZ03zBjldLrAi0EHWvaY7G3C1wh81fPX17ehZ7xKM0S//cxAt4CTUwyUwyv23LaCPQuXlQKEk7wxc8HVo/2v3Wcsq95h/y4XPVx8JHQBLGcYvQGnOMMAnIGYnVY+bNAbgSZkSFZVUx5BO2ILJPXBliTPbPBioRoz93UKfgPrC2ZqedjyWzCVMl9wLkYufd2OWbMI8D0sPqU3vIcgg0h7jgxY2lOKW2saLI8bEAuVT7NT+5j5uczeQStcztxaT2LaYwgvAO5gxQNW7CeXTj15IzN4CNJS/yuWpNykzK5elcIAczK/1TjN1F8i7GyAgwyykNu02mgmrE8iQBdrtFg0gtE1OU1szh09faxc9JoEx1E2709J/RBq7eX91JYH1z7gQVl/PfgOsZAW9medTXucYxHsBhkvdjmg3Fj6EY9xwvCgysGU7LrRIc272bgypUZzI5ZnJ4QjBtmmPGENClSkm76yeCcskh2D0mrzQBrHfDIY6SqD4+LF56N7NwUZ5PbiNtuPi5R5jjXNnXRuHNTQ2c/Z8wfXrd0uWsi9p9twNv4MLArNqh4BCra8yVnmBcgUaf9R4KF/33KLHln9Mf67KVH832xg9b1YFLRyRm/tSJvr4oxtu8hdvgp/HcXMJIit+jzRoJEOnQYXJGVf5m7TmYYuV9ce4xoHML+W3w6i0RmngJm58+KUcG5f6xfyJ64/NuLoKCEJTeml419NTAl83nw2SXD/Tk85P/C4GN3skWDxK5B2YX3AbyxiiYzh/UGpkbzihVgRtQrvbc7ndCFi08ajo6KlV0VrAUxKYOAyWqcAu58NHFfn9Y0VWYj/HMqdU7bRr6wjE258UdYYZxg/dyBjjMPUUlwh+ut9ApoeDHAkFKfzoVkcarnNtj1zETLIHJw6qdpwBAv7NDZYYTTk9g1LJfee3IiVLNs+qM22b+hzBWrDQgRgpn9A7gyuQziMzKKkvDxFYaY29pgjvxDFzvLgELdkTVWcx0Lqhs+cwzDkUTtzILEMOG3PjkeJTt53jX85yOeJUKtDO6HNCHtICnap93S7uKx9/8KcOC1bHueu0=");
//        Spire.License.LicenseProvider.SetLicenseFileName("license1.elic.xml");
//        Spire.License.LicenseProvider.LoadLicense();
    }

}